gufrufr:
    resource: "@GUFRUFRBundle/Resources/config/routing.yml"
    prefix:   /GestionUFR

gprc_parc:
    resource: "@GPRCParcBundle/Resources/config/routing.yml"
    prefix:   /GestionParc

gusr_user:
    resource: "@GUSRUserBundle/Resources/config/routing.yml"
    prefix:   /GestionUser

gprof_profile:
    resource: "@GPROFProfileBundle/Resources/config/routing.yml"
    prefix:   /GestionProfil

log_login:
    resource: "@LOGLoginBundle/Resources/config/routing.yml"
    prefix:   /Signin

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
