r_com:
    resource: "@RComBundle/Resources/config/routing.yml"
    prefix:   /

rasp_rasp:
    resource: "@RASPRaspBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"