#oc_platform_homepage:
#    path:     /platform
#    defaults: { _controller: OCPlatformBundle:Default:index }


#hello_the_world:
#    path: /hello-world
#    defaults: {_controller: OCPlatformBundle:Advert:index }

# prefix /platform already defined in app/routing.yml
oc_platform_home:
    path:       /{page}
    defaults:   { _controller: OCPlatformBundle:Advert:index, page: 1 }
    requirements:
        page: \d*

oc_platform_view:
    path:       /advert/{id}
    defaults:   { _controller: OCPlatformBundle:Advert:view }

oc_platform_view_slug:
    # Exemple: http://127.0.0.1:8000/app_dev.php/platform/2015/kikou.diff
    path:		/{year}/{slug}.{format}
    defaults:	
        { _controller: OCPlatformBundle:Advert:viewSlug, format: html }
    requirements:
        year: \d{4}
        format: html|diff

oc_platform_error_notFound:
    path:       /error_notFound
    defaults:   { _controller: OCPlatformBundle:Advert:error_notFound }

oc_platform_redirect:
    path:       /imlost
    defaults:   {_controller: OCPlatformBundle:Advert:redirectPlz}

oc_platform_getJsonData:
    path:       /jsonPlz
    defaults:   {_controller: OCPlatformBundle:Advert:getJsonData}

oc_platform_add:
    path:        /add
    defaults:   { _controller: OCPlatformBundle:Advert:add }

oc_platform_edit:
    path:       /edit/{id}
    defaults: { _controller: OCPlatformBundle:Advert:edit}
    requirements: { id: \d+ }

oc_platform_delete:
    path:       /delete/{id}
    defaults:   { _controller: OCPlatformBundle:Advert:delete}
    requirements: { id: \d+ }

oc_platform_helloWorld:
    path:		/helloWorld
    defaults:	{ _controller: OCPlatformBundle:Advert:helloWorld }

