rasp_rasp_homepage:
    path:     /
    defaults: { _controller: RASPRaspBundle:Default:index }

rasp_listRasp:
    path:   /rasp/rasps/{ufr_id}
    defaults:
        _controller: RASPRaspBundle:Rasp:listRasp
    requirements:
        ufr_id: \d+

rasp_showRasp:
    path:   /rasp/rasp/{rasp_id}
    defaults:
        _controller: RASPRaspBundle:Rasp:showRasp
    requirements:
        rasp_id:  \d+

rasp_editRasp:
    path:   /rasp/editRasp/{rasp_id}
    defaults:
        _controller:  RASPRaspBundle:Rasp:editRasp
    requirements:
        rasp_id:  \d+

admin_homepage:
    path:   /admin_/
    defaults:
        _controller: RASPRaspBundle:Default:adminIndex

admin_users:
    path:    /admin_/users
    defaults:
        _controller: RASPRaspBundle:Gestion:users

user_editPassord:
    path:    /userPassword/{user_id}
    defaults:
        _controller: RASPRaspBundle:Gestion:userPassword
    requirements:
        user_id: \d+

admin_showUser:
    path:    /admin_/user/{user_id}
    defaults:
        _controller: RASPRaspBundle:Gestion:user
    requirements:
        user_id: \d+

admin_editUser:
    path:    /admin_/editUser/{user_id}
    defaults:
        _controller: RASPRaspBundle:Gestion:editUser
    requirements:
        user_id: \d+

admin_userSuccess:
    path:    /admin_/userSuccess/{user_id}
    defaults:
        _controller: RASPRaspBundle:Gestion:userSuccess
    requirements:
        user_id: \d+

admin_createUser:
    path:    /admin_/createUser
    defaults:
        _controller: RASPRaspBundle:Gestion:createUser

admin_toggleUser:
    path:   /admin_/toggleUser/{user_id}
    defaults:
        _controller: RASPRaspBundle:Gestion:toggleUser
    requirements:
        user_id: \d+

admin_createUfr:
    path:   /admin_/createUfr
    defaults:
        _controller:  RASPRaspBundle:Ufr:createUfr

admin_listUfrs:
    path:   /admin_/ufrs
    defaults:
        _controller:  RASPRaspBundle:Ufr:ufrs

admin_showUfr:
    path:   /showUfr/{ufr_id}
    defaults:
        _controller:  RASPRaspBundle:Ufr:showUfr
    requirements:
        ufr_id: \d+

admin_editUfr:
    path:   /admin_/editUfr/{ufr_id}
    defaults:
        _controller:  RASPRaspBundle:Ufr:editUfr
    requirements:
        ufr_id: \d+