r_com_homepage:
    path:     /wthit/
    defaults: { _controller: RComBundle:Default:index }

r_com_announce:
    path:     /wthit/whatsup
    defaults: { _controller: RComBundle:Default:whatsup }

r_com_queryAction:
    path:     /wthit/imbored
    defaults: { _controller: RComBundle:Default:imbored }