r_com_homepage:
    path:     /wthit/
    defaults: { _controller: RComBundle:Default:index }

r_com_announce:
    path:     /wthit/whatsup
    defaults: { _controller: RComBundle:Default:whatsup }

r_com_queryAction:
    path:     /wthit/imbored
    defaults: { _controller: RComBundle:Default:imbored }

r_com_deleteAction:
    path:     /wthit/deleteAction/{rasp_id}/{action_id}
    defaults:
        _controller: RComBundle:Default:deleteAction
    requirements:
        rasp_id:    \d+
        action_id:  \d+

r_com_rebootPlz:
    path:     /wthit/rebootPlz/{rasp_id}
    defaults:
        _controller:    RComBundle:Default:rebootPlz
    requirements:
        rasp_id:  \d+

r_com_updatePlz:
    path:    /wthit/updatePlz/{rasp_id}
    defaults:
        _controller:    RComBundle:Default:updatePlz
    requirements:
        rasp_id:  \d+

r_com_upgradePlz:
    path:    /wthit/upgradePlz/{rasp_id}
    defaults:
        _controller:    RComBundle:Default:upgradePlz
    requirements:
        rasp_id:  \d+

r_com_personalPlz:
    path:    /wthit/personalPlz/{rasp_id}
    defaults:
        _controller:    RComBundle:Default:personalPlz
    requirements:
        rasp_id:  \d+