<?php

namespace RASP\RaspBundle\Entity;

/**
 * RaspberryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaspberryRepository extends \Doctrine\ORM\EntityRepository
{
}
