<?php
/*
 * Created by sydney_manjaro the 04/01/17
 */

namespace RASP\RaspBundle\Entity;

/**
 * UfrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UfrRepository extends \Doctrine\ORM\EntityRepository
{
}
